name: bhabi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.8.12
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  
  # Google Sign In
  google_sign_in: ^6.2.2
  
  # Other dependencies
  provider: ^6.1.1
  clipboard: ^0.1.3
  http: ^1.1.2
  js: ^0.6.7
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # 👈 added for icon generation

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"     # 👈 path to your icon image

flutter:
  uses-material-design: true
  assets:
    - assets/card_back.png
    - assets/google_logo.png
    - assets/deck2.webp
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
