name: bhabi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  js: ^0.6.7
  cloud_firestore: ^4.7.0
  firebase_database: ^10.2.0
  clipboard: ^0.1.3
  http: ^0.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
