// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5W5TPweAzMV_kgXL5qM9nRa3w-Yshw2U',
    appId: '1:540566410414:web:79dc0e9cb66575cd2b493f',
    messagingSenderId: '540566410414',
    projectId: 'bhabhi-b70b9',
    authDomain: 'bhabhi-b70b9.firebaseapp.com',
    databaseURL: 'https://bhabhi-b70b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhabhi-b70b9.firebasestorage.app',
    measurementId: 'G-72R2C810HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWE3NwmCeYGW1yfu512KWhuIzZ5i5Q1_U',
    appId: '1:540566410414:android:2d2f371eaf8142652b493f',
    messagingSenderId: '540566410414',
    projectId: 'bhabhi-b70b9',
    databaseURL: 'https://bhabhi-b70b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhabhi-b70b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWEEc44iBeo4atF4e8KuGzY2P1I847x2s',
    appId: '1:540566410414:ios:07dfa601b180bd9b2b493f',
    messagingSenderId: '540566410414',
    projectId: 'bhabhi-b70b9',
    databaseURL: 'https://bhabhi-b70b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhabhi-b70b9.firebasestorage.app',
    iosBundleId: 'com.example.bhabi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWEEc44iBeo4atF4e8KuGzY2P1I847x2s',
    appId: '1:540566410414:ios:07dfa601b180bd9b2b493f',
    messagingSenderId: '540566410414',
    projectId: 'bhabhi-b70b9',
    databaseURL: 'https://bhabhi-b70b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhabhi-b70b9.firebasestorage.app',
    iosBundleId: 'com.example.bhabi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5W5TPweAzMV_kgXL5qM9nRa3w-Yshw2U',
    appId: '1:540566410414:web:bc84e659b192034a2b493f',
    messagingSenderId: '540566410414',
    projectId: 'bhabhi-b70b9',
    authDomain: 'bhabhi-b70b9.firebaseapp.com',
    databaseURL: 'https://bhabhi-b70b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhabhi-b70b9.firebasestorage.app',
    measurementId: 'G-LXD3VR2RNF',
  );
}
